### ISSUE TITLE
Add ボタン押下しても入力欄が消えないので登録したかどうかわからない

### ISSUE THREAD

**Issue by nodokaodayaka** [nodokaodayaka/redux-study#15]
# 対象画面

## URL

http://localhost:3000

# 操作

## オペレーション

1. 入力欄に文字を入力
2. Addボタンを押下
3. 入力欄に入力した文字が残っている

# 完了条件

- [x] 入力したタイトルをAddボタンで登録した場合、登録できたときには、入力欄が消えること

**Comment by nodokaodayaka** [comment]
どの画面かわからない

**Comment by nodokaodayaka** [comment]
完了はどういう状態？

**Comment by izupu02** [comment]
Add押したあとにGet Todolist〜のボタン押さないとTodoが表示されない

**Comment by hirayama-tatsuya** [comment]
> Add押したあとにGet Todolist〜のボタン押さないと表示されない

この対応は別のプロダクトバックログで対応します
